test_top.v
../../source/CPU_define.v
../../source/top.v
../../source/IF_stage.v
../../source/IF_ID.v
../../source/ID_stage.v
../../source/controller.v
../../source/regfile.v
../../source/ID_EXE.v
../../source/EXE_stage.v
../../source/alu.v
../../source/PC.v
../../source/SRAM256x32s_m.v
+define+PRESIM
+access+r
