//==============================================================================
// Hierarchical dofile generated by Conformal LEC
// Version: 20.10-p100 (01-May-2020) (64 bit executable)
//------------------------------------------------------------------------------
// The command 'set module property' sets the instance context for the current
// root module. It is intended only for hierarchical comparison, and should
// not be modified by the user.
//==============================================================================

set system mode setup
// Comparing module 'PC'
set root module PC -Golden
set root module PC -Revised
set module property -instance /top0/IF_stage/PC -Golden
set module property -instance /top0/IF_stage/PC -Revised
report black box -NOHidden
set system mode lec
analyze multiplier -cdp_info; analyze datapath -merge -share -effort medium -verbose
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box PC -module -hier -Golden
add black box PC -module -hier -Revised
// Comparing module 'IF_stage'
set root module IF_stage -Golden
set root module IF_stage -Revised
set module property -instance /top0/IF_stage -Golden
set module property -instance /top0/IF_stage -Revised
report black box -NOHidden
set system mode lec
analyze multiplier -cdp_info; analyze datapath -merge -share -effort medium -verbose
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box IF_stage -module -hier -Golden
add black box IF_stage -module -hier -Revised
// Comparing module 'IF_ID'
set root module IF_ID -Golden
set root module IF_ID -Revised
set module property -instance /top0/IF_ID -Golden
set module property -instance /top0/IF_ID -Revised
report black box -NOHidden
set system mode lec
analyze multiplier -cdp_info; analyze datapath -merge -share -effort medium -verbose
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box IF_ID -module -hier -Golden
add black box IF_ID -module -hier -Revised
// Comparing module 'dsram'
set root module dsram -Golden
set root module dsram -Revised
set module property -instance /top0/ID_stage/dcache -Golden
set module property -instance /top0/ID_stage/dcache -Revised
report black box -NOHidden
set system mode lec
analyze multiplier -cdp_info; analyze datapath -merge -share -effort medium -verbose
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box dsram -module -hier -Golden
add black box dsram -module -hier -Revised
// Comparing module 'ID_EXE'
set root module ID_EXE -Golden
set root module ID_EXE -Revised
set module property -instance /top0/ID_EXE -Golden
set module property -instance /top0/ID_EXE -Revised
report black box -NOHidden
set system mode lec
analyze multiplier -cdp_info; analyze datapath -merge -share -effort medium -verbose
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box ID_EXE -module -hier -Golden
add black box ID_EXE -module -hier -Revised
// Comparing module 'top'
set root module top -Golden
set root module top -Revised
set module property -instance /top0 -Golden
set module property -instance /top0 -Revised
report black box -NOHidden
set system mode lec
analyze multiplier -cdp_info; analyze datapath -merge -share -effort medium -verbose
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box top -module -hier -Golden
add black box top -module -hier -Revised
// Root modules
// Comparing module 'top_pipe'
set root module top_pipe -Golden
set root module top_pipe -Revised
set module property -instance / -Golden
set module property -instance / -Revised
report black box -NOHidden
set system mode lec
analyze multiplier -cdp_info; analyze datapath -merge -share -effort medium -verbose
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
report hier_compare result
report hier_compare result -Non_equivalent
report hier_compare result -Abort
report hier_compare result -Uncompared
// _END_OF_LEC_HIERARCHICAL_DOFILE_
