# testbench
test_top.v

# netlist generated by Design Compiler
../syn/netlist/top_pipe_syn.v

# Logic Gate models
-v /usr/cadtool/cad/synopsys/SAED32_EDK/lib/stdcell_hvt/verilog/saed32nm_hvt.v

+define+GATESIM
+access+r
